import express from 'express';
import { createServer } from 'node:http';
import { randomBytes, randomInt, scryptSync, timingSafeEqual } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Server } from 'socket.io';
import { createServer as createViteServer } from 'vite';
import { createGame, roll, buy, passProperty, build, endTurn, type GameState } from './src/game/engine';
import { BOARD, RULES } from './src/game/rules';

const app=express();app.use((req,res,next)=>{const origin=req.headers.origin;if(origin){try{if(new URL(origin).host!==req.headers.host)return res.status(403).json({error:'Cross-origin request rejected.'});}catch{return res.status(403).json({error:'Invalid origin.'});}}next();});app.use(express.json({limit:'32kb'}));
const httpServer=createServer(app);const io=new Server(httpServer,{cors:{origin:true,credentials:true}});
const root=path.dirname(fileURLToPath(import.meta.url));const dataDir=process.env.SCAMCITY_DATA_DIR||path.join(root,'data');
interface Account{ id:string; username:string; normalized:string; displayName:string; salt:string; passwordHash:string; friends:string[]; createdAt:string }
type PublicUser=Pick<Account,'id'|'username'|'displayName'>;
interface Room{ code:string; hostId:string; members:PublicUser[]; game:GameState|null; createdAt:string; turnDeadline:number|null; timer?:ReturnType<typeof setTimeout> }
let accounts:Account[]=[];const sessions=new Map<string,string>();const socketsByUser=new Map<string,Set<string>>();const rooms=new Map<string,Room>();const chatRate=new Map<string,number[]>();
const publicUser=({id,username,displayName}:Account):PublicUser=>({id,username,displayName});
const cookieValue=(header:string|undefined,name:string)=>header?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1);
const sessionUser=(cookie:string|undefined)=>{const token=cookieValue(cookie,'scam_session');const id=token?sessions.get(decodeURIComponent(token)):undefined;return id?accounts.find(a=>a.id===id):undefined;};
const onlineIds=()=>new Set(socketsByUser.keys());
const emitPresence=()=>io.emit('presence:update',[...onlineIds()]);
async function saveAccounts(){await mkdir(dataDir,{recursive:true});await writeFile(path.join(dataDir,'accounts.json'),JSON.stringify(accounts,null,2),'utf8');}
try{accounts=JSON.parse(await readFile(path.join(dataDir,'accounts.json'),'utf8')) as Account[]}catch{accounts=[];}
function issueSession(res:express.Response,user:Account){const token=randomBytes(32).toString('base64url');sessions.set(token,user.id);const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`scam_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${secure}`);res.json({user:publicUser(user)});}
function requireUser(req:express.Request,res:express.Response){const user=sessionUser(req.headers.cookie);if(!user){res.status(401).json({error:'Please log in again.'});return null;}return user;}
app.post('/api/auth/signup',async(req,res)=>{const username=String(req.body?.username||'').trim(),normalized=username.toLowerCase(),password=String(req.body?.password||''),displayName=String(req.body?.displayName||username).trim().slice(0,24);if(!/^[a-zA-Z0-9_]{3,18}$/.test(username))return res.status(400).json({error:'Username must be 3–18 letters, numbers or underscores.'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters.'});if(accounts.some(a=>a.normalized===normalized))return res.status(409).json({error:'That username is already taken.'});const salt=randomBytes(16).toString('hex'),user:Account={id:randomBytes(12).toString('hex'),username,normalized,displayName:displayName||username,salt,passwordHash:scryptSync(password,salt,64).toString('hex'),friends:[],createdAt:new Date().toISOString()};accounts.push(user);await saveAccounts();issueSession(res,user);});
app.post('/api/auth/login',(req,res)=>{const normalized=String(req.body?.username||'').trim().toLowerCase(),password=String(req.body?.password||''),user=accounts.find(a=>a.normalized===normalized);if(!user)return res.status(401).json({error:'Username or password is incorrect.'});const actual=scryptSync(password,user.salt,64),expected=Buffer.from(user.passwordHash,'hex');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return res.status(401).json({error:'Username or password is incorrect.'});issueSession(res,user);});
app.get('/api/auth/me',(req,res)=>{const user=sessionUser(req.headers.cookie);res.json({user:user?publicUser(user):null});});
app.post('/api/auth/logout',(req,res)=>{const token=cookieValue(req.headers.cookie,'scam_session');if(token)sessions.delete(decodeURIComponent(token));res.setHeader('Set-Cookie','scam_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true});});
app.get('/api/people',(req,res)=>{const user=requireUser(req,res);if(!user)return;const query=String(req.query.q||'').trim().toLowerCase();if(query.length<2)return res.json({people:[]});const friendSet=new Set(user.friends);res.json({people:accounts.filter(a=>a.id!==user.id&&a.normalized.includes(query)).slice(0,12).map(a=>({...publicUser(a),online:socketsByUser.has(a.id),isFriend:friendSet.has(a.id)}))});});
app.get('/api/friends',(req,res)=>{const user=requireUser(req,res);if(!user)return;res.json({friends:user.friends.map(id=>accounts.find(a=>a.id===id)).filter((a):a is Account=>!!a).map(a=>({...publicUser(a),online:socketsByUser.has(a.id)}))});});
app.post('/api/friends',(req,res)=>{const user=requireUser(req,res);if(!user)return;const name=String(req.body?.username||'').trim().toLowerCase(),other=accounts.find(a=>a.normalized===name);if(!other)return res.status(404).json({error:'No account found with that username.'});if(other.id===user.id)return res.status(400).json({error:'You cannot add yourself.'});if(!user.friends.includes(other.id))user.friends.push(other.id);if(!other.friends.includes(user.id))other.friends.push(user.id);void saveAccounts();for(const sid of socketsByUser.get(user.id)||[])io.to(sid).emit('friends:update',user.friends.map(id=>accounts.find(a=>a.id===id)).filter(Boolean).map(a=>({...publicUser(a!),online:socketsByUser.has(a!.id)})));for(const sid of socketsByUser.get(other.id)||[])io.to(sid).emit('friends:update',other.friends.map(id=>accounts.find(a=>a.id===id)).filter(Boolean).map(a=>({...publicUser(a!),online:socketsByUser.has(a!.id)})));res.json({friend:{...publicUser(other),online:socketsByUser.has(other.id)}});});
function roomPayload(room:Room){return{code:room.code,hostId:room.hostId,started:!!room.game,members:room.members,game:room.game,turnDeadline:room.turnDeadline};}
function broadcastRoom(room:Room){io.to(room.code).emit('room:update',roomPayload(room));}
function armTurnTimer(room:Room,duration:number){if(room.timer)clearTimeout(room.timer);if(!room.game||room.game.phase==='finished'){room.turnDeadline=null;broadcastRoom(room);return;}room.turnDeadline=Date.now()+duration*1000;broadcastRoom(room);room.timer=setTimeout(()=>{if(!room.game||room.game.phase==='finished')return;let next=room.game;if(next.phase==='roll')next=roll(next).state;if(next.phase==='decision'){const tile=BOARD[next.players[next.turn].position];if(['city','transport','utility'].includes(tile.kind)&&!next.owners[tile.id])next=passProperty(next);next=endTurn(next);}room.game=next;io.to(room.code).emit('game:state',next);armTurnTimer(room,next.phase==='decision'?RULES.timing.propertySeconds:RULES.timing.turnSeconds);},duration*1000);}
function code(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>alphabet[randomInt(alphabet.length)]).join('');}
function shuffle<T>(items:T[]){const result=[...items];for(let i=result.length-1;i>0;i--){const j=randomInt(i+1);[result[i],result[j]]=[result[j],result[i]];}return result;}
function ackError(ack:unknown,message:string){if(typeof ack==='function')(ack as (v:unknown)=>void)({ok:false,error:message});}
io.use((socket,next)=>{const origin=socket.request.headers.origin;if(origin){try{if(new URL(origin).host!==socket.request.headers.host)return next(new Error('Cross-origin socket rejected.'));}catch{return next(new Error('Invalid socket origin.'));}}const user=sessionUser(socket.request.headers.cookie);if(!user)return next(new Error('Please log in to join a room.'));socket.data.user=user;next();});
io.on('connection',socket=>{const user=socket.data.user as Account;const sockets=socketsByUser.get(user.id)||new Set<string>();sockets.add(socket.id);socketsByUser.set(user.id,sockets);emitPresence();socket.emit('friends:update',user.friends.map(id=>accounts.find(a=>a.id===id)).filter(Boolean).map(a=>({...publicUser(a!),online:socketsByUser.has(a!.id)})));
 socket.on('room:create',(ack)=>{let id=code();while(rooms.has(id))id=code();const room:Room={code:id,hostId:user.id,members:[publicUser(user)],game:null,createdAt:new Date().toISOString(),turnDeadline:null};rooms.set(id,room);socket.join(id);socket.data.roomCode=id;socket.emit('room:update',roomPayload(room));if(typeof ack==='function')ack({ok:true,room:roomPayload(room)});});
 socket.on('room:join',(raw,ack)=>{const id=String(raw||'').trim().toUpperCase(),room=rooms.get(id);if(!room)return ackError(ack,'Room code not found.');if(room.game)return ackError(ack,'That game has already started.');if(room.members.length>=6)return ackError(ack,'This room is full (6 players max).');if(!room.members.some(m=>m.id===user.id))room.members.push(publicUser(user));socket.join(id);socket.data.roomCode=id;io.to(id).emit('room:update',roomPayload(room));if(typeof ack==='function')ack({ok:true,room:roomPayload(room)});});
 socket.on('room:invite',(friendId,ack)=>{const id=socket.data.roomCode as string|undefined,room=id?rooms.get(id):undefined;if(!room)return ackError(ack,'Create or join a room first.');if(!user.friends.includes(String(friendId)))return ackError(ack,'Only friends can be invited.');const targetSockets=socketsByUser.get(String(friendId));if(!targetSockets?.size)return ackError(ack,'Your friend is offline.');for(const targetSocket of targetSockets)io.to(targetSocket).emit('game:invite',{from:user.displayName,roomCode:id});if(typeof ack==='function')ack({ok:true});});
 socket.on('chat:send',(raw,ack)=>{const id=socket.data.roomCode as string|undefined,room=id?rooms.get(id):undefined;if(!room)return ackError(ack,'Join a room to use game chat.');const text=String(raw||'').trim().slice(0,240);if(!text)return ackError(ack,'Message is empty.');const now=Date.now(),recent=(chatRate.get(user.id)||[]).filter(t=>now-t<10000);if(recent.length>=6)return ackError(ack,'Slow down a moment before sending another message.');recent.push(now);chatRate.set(user.id,recent);const message={username:user.displayName,text,timestamp:new Date(now).toISOString()};io.to(id!).emit('chat:message',message);if(typeof ack==='function')ack({ok:true});});
 socket.on('room:rematch',(ack)=>{const id=socket.data.roomCode as string|undefined,room=id?rooms.get(id):undefined;if(!room?.game||room.hostId!==user.id)return ackError(ack,'Only the host can start a rematch.');if(room.game.phase!=='finished')return ackError(ack,'The current game is not finished.');room.members=[...room.members.slice(1),room.members[0]];room.game=createGame(room.members.map(m=>m.displayName));io.to(id!).emit('game:state',room.game);armTurnTimer(room,RULES.timing.turnSeconds);if(typeof ack==='function')ack({ok:true});});
 socket.on('room:leave',()=>{  const id=socket.data.roomCode as string|undefined,room=id?rooms.get(id):undefined;if(!room)return;room.members=room.members.filter(m=>m.id!==user.id);socket.leave(id!);delete socket.data.roomCode;if(!room.members.length){if(room.timer)clearTimeout(room.timer);rooms.delete(id!);}else{if(room.hostId===user.id)room.hostId=room.members[0].id;io.to(id!).emit('room:update',roomPayload(room));}});
 socket.on('room:start',(ack)=>{const id=socket.data.roomCode as string|undefined,room=id?rooms.get(id):undefined;if(!room)return ackError(ack,'Join a room first.');if(room.hostId!==user.id)return ackError(ack,'Only the host can start this game.');if(room.members.length<2)return ackError(ack,'Invite at least one friend first.');if(room.game)return ackError(ack,'Game already started.');const shuffled=shuffle(room.members);room.members=shuffled;room.game=createGame(shuffled.map(m=>m.displayName));io.to(id!).emit('game:state',room.game);armTurnTimer(room,RULES.timing.turnSeconds);if(typeof ack==='function')ack({ok:true});});
 socket.on('game:command',(command,ack)=>{const id=socket.data.roomCode as string|undefined,room=id?rooms.get(id):undefined;if(!room?.game)return ackError(ack,'No active game.');const slot=room.members.findIndex(m=>m.id===user.id);if(slot<0||room.game.turn!==slot)return ackError(ack,'NOT_YOUR_TURN');let next=room.game;switch(command?.type){case'ROLL':next=roll(next).state;break;case'BUY_PROPERTY':next=buy(next);break;case'PASS_PROPERTY':next=passProperty(next);break;case'BUILD':next=build(next,String(command.propertyId));break;case'END_TURN':next=endTurn(next);break;default:return ackError(ack,'Unknown game command.');}if(next===room.game)return ackError(ack,'Action is not valid in this phase or state.');room.game=next;io.to(id!).emit('game:state',next);if(next.phase==='finished')armTurnTimer(room,RULES.timing.turnSeconds);else if(command.type==='ROLL')armTurnTimer(room,RULES.timing.propertySeconds);else if(command.type==='END_TURN')armTurnTimer(room,RULES.timing.turnSeconds);if(typeof ack==='function')ack({ok:true,state:next});});
 socket.on('disconnect',()=>{const set=socketsByUser.get(user.id);set?.delete(socket.id);if(!set?.size)socketsByUser.delete(user.id);emitPresence();});
});
if(process.env.NODE_ENV==='production'){app.use(express.static(path.join(root,'dist')));app.get('*',(_req,res)=>res.sendFile(path.join(root,'dist','index.html')));}else{const vite=await createViteServer({server:{middlewareMode:true,allowedHosts:true},appType:'spa'});app.use(vite.middlewares);}
const port=Number(process.env.PORT||3000);httpServer.listen(port,'0.0.0.0',()=>console.log(`Scam City web + realtime server listening on ${port}`));
